In [1]:
import torch 

torch.__version__

'2.1.2+cpu'

## Ejercicio 2

Crea un tensor aleatorio con forma .(7, 7)

In [4]:
tensor_1 = torch.rand(2,3)

print(tensor_1)
print(tensor_1.shape)

tensor([[0.2484, 0.6295, 0.4565],
        [0.9373, 0.5963, 0.8266]])
torch.Size([2, 3])


## Ejercicio 3

Realiza una multiplicación matricial en el tensor de 2 con otro tensor aleatorio con forma (pista: es posible que tengas que transponer el segundo tensor).(1, 7)

In [10]:
tensor_2 = torch.rand(2,3)

# tensor_1 @ tensor_2.T
# tensor_1.matmul(tensor_2.T)
tensor_1.mm(tensor_2.T)

tensor([[0.9927, 0.8923],
        [1.4914, 1.1728]])

## Ejercicio 4

Establezca la semilla aleatoria en y repita los ejercicios 2 y 3.0

In [14]:
torch.manual_seed(42)

tensor_1 = torch.rand(2,3)
tensor_2 = torch.rand(2,3)

print(tensor_1)
print(tensor_2)

print(torch.mm(tensor_1, tensor_2.T))

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])
tensor([[1.3127, 1.1999],
        [1.1213, 0.8494]])


In [20]:
tensor_x = torch.tensor([1,2,3])

print(f"El valor maximo esta en la posicion: {tensor_x.argmax()} y es: {tensor_x.max()}")
print(f"El valor minimo esta en la posicion: {tensor_x.argmin()} y es: {tensor_x.min()}")

El valor maximo esta en la posicion: 2 y es: 3
El valor minimo esta en la posicion: 0 y es: 1


## Ejercicio 5

Hablando de semillas aleatorias, vimos cómo configurarlo, pero ¿existe un equivalente de GPU? (Sugerencia: tendrás que consultar la documentación para esto). Si lo hay, establezca la semilla aleatoria de GPU en .torch.manual_seed()torch.cuda1234

In [ ]:
torch.cuda.manual_seed(1234)

## Ejercicio 6

Crea dos tensores aleatorios de forma y envíalos a la GPU (necesitarás acceso a una GPU para esto). Se establece al crear los tensores (no tiene que ser la semilla aleatoria de la GPU).(2, 3)torch.manual_seed(1234)