In [1]:
import torch

torch.__version__

'2.1.2+cpu'

## Escalares, Vectores, Matrices y Tensores

In [15]:
escalar = torch.tensor(7)

# --> Visualizacion de un escalar
print(escalar)
print(escalar.ndim)
print(escalar.item())

tensor(7)
0
7


In [12]:
vector = torch.tensor([1, 2, 3, 4, 5])

# --> Visualizacion de un vector
print(vector)
print(vector.ndim)

tensor([1, 2, 3, 4, 5])
1


In [17]:
MATRIX = torch.tensor([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
    ])

# --> Visualizacion de una matriz
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
2
torch.Size([3, 3])


In [19]:
# Los tensores pueden representar casi cualquier cosa
TENSOR = torch.tensor([[
    [1, 2, 3], [4, 5, 6], [7, 8, 9]
    ]])

# --> Visualizacion de un tensor
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])


## Tensores Aleatorios

In [23]:
random_tensor = torch.rand(3, 3)

# --> Visualizacion de un tensor aleatorio
print(random_tensor)

tensor([[0.1648, 0.2922, 0.3445],
        [0.6724, 0.1565, 0.7131],
        [0.7027, 0.1021, 0.2640]])


In [25]:
random_tensor2 = torch.randn(size=(224, 224, 3))

# --> Visualizacion de un tensor aleatorio
# print(random_tensor2)
print(random_tensor2.shape)

torch.Size([224, 224, 3])


## Tensores diferentes

In [26]:
tensor_ceros = torch.zeros(size=(3, 3))

# --> Visualizacion de un tensor de ceros
print(tensor_ceros)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [27]:
tensor_unos = torch.ones(size=(3, 3))

# --> Visualizacion de un tensor de unos
print(tensor_unos)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [29]:
tensor_rango = torch.arange(start=0, end=5, step=1)

# --> Visualizacion de un tensor de rango
print(tensor_rango)
print(tensor_rango.shape)
print(tensor_rango.ndim)
print(tensor_rango.dtype)
print(tensor_rango.device)

tensor([0, 1, 2, 3, 4])
torch.Size([5])
1
torch.int64
cpu


## Operaciones básicas

In [34]:
tensor_ejemplo = torch.tensor([1, 2, 3])

# --> Visualizacion de un tensor de ejemplo
print(tensor_ejemplo + 10)
print(tensor_ejemplo - 10)
print(tensor_ejemplo * 10)
print(tensor_ejemplo / 10)

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


## Multiplicacion de matrices

In [37]:
print(tensor_ejemplo * tensor_ejemplo)
print(torch.matmul(tensor_ejemplo, tensor_ejemplo))
print(tensor_ejemplo @ tensor_ejemplo)

tensor([1, 4, 9])
tensor(14)
tensor(14)


In [50]:
tensor_a = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
    ], dtype=torch.float32)
tensor_b = torch.tensor([
    [4, 5, 6],
    [7, 8, 9]
    ], dtype=torch.float32)

# --> Forma de los tensores
print("[+] Shape of tensor_a:", tensor_a.shape)
print("[+] Shape of tensor_b:", tensor_b.shape)
print("[+] Shape of tensor_b.T:", tensor_b.T.shape)


# --> Asi no
# torch.matmul(tensor_a, tensor_b)

# --> Asi si
# print(torch.mm(tensor_a, tensor_b.T))
tensor_a @ tensor_b.T



[+] Shape of tensor_a: torch.Size([2, 3])
[+] Shape of tensor_b: torch.Size([2, 3])
[+] Shape of tensor_b.T: torch.Size([3, 2])


tensor([[ 32.,  50.],
        [ 77., 122.]])

In [56]:
torch.manual_seed(42)

linear = torch.nn.Linear(
    in_features=2,      # Caracteristicas de entrada
    out_features=6      # Caracteristicas de salida
)
x = tensor_a.T
output = linear(x)
print(f"[+] Forma de entrada: {x.shape}\n")
print(f"[+] Salida:\n{output}\n\n [+]Forma de salida: {output.shape}")

[+] Forma de entrada: torch.Size([3, 2])

[+] Salida:
tensor([[ 3.4106,  2.5283,  0.7568,  1.2170, -0.9066,  1.2485],
        [ 4.5382,  3.0122,  0.7445,  1.2880, -0.8020,  1.9955],
        [ 5.6657,  3.4961,  0.7323,  1.3590, -0.6974,  2.7424]],
       grad_fn=<AddmmBackward0>)

 [+]Forma de salida: torch.Size([3, 6])


## Mover a GPU

In [64]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
print("Despues de mover el tensor a la GPU".center(50, "-"))
print(tensor_on_gpu, tensor_on_gpu.device)

cpu
tensor([1, 2, 3]) cpu
-------Despues de mover el tensor a la GPU--------
tensor([1, 2, 3]) cpu
